#***NumPy and Basic Pandas***

#Introduction
Now that we have introduced the fundamentals of Python, it's time to learn about NumPy and Pandas.

#NumPy
NumPy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. It also has strong integration with Pandas, which is another powerful tool for manipulating financial data.

Python packages like NumPy and Pandas contain classes and methods which we can use by importing the package:

In [1]:
import numpy as np

#Basic NumPy Arrays
A NumPy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. Here we make an array by passing a list of Apple stock prices:

In [2]:
price_list = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
price_array = np.array(price_list)
print(price_array, type(price_array))

[143.73 145.83 143.68 144.02 143.5  142.62] <class 'numpy.ndarray'>


In [3]:
lista_precios = [20.43, 75.83, 142.68, 154.02, 5253.5, 142.62]
arreglo_precios = np.array(lista_precios)
print(arreglo_precios, type(arreglo_precios))

[  20.43   75.83  142.68  154.02 5253.5   142.62] <class 'numpy.ndarray'>


Notice that the type of array is "ndarray" which is a multi-dimensional array. If we pass np.array() a list of lists, it will create a 2-dimensional array.



In [4]:
Ar = np.array([[1,3],[2,4]])
print(Ar, type(Ar))

[[1 3]
 [2 4]] <class 'numpy.ndarray'>


In [5]:
Arreglo = np.array([[8,7],[6,5],[2,66]])
print(Arreglo, type(Arreglo))

[[ 8  7]
 [ 6  5]
 [ 2 66]] <class 'numpy.ndarray'>


We get the dimensions of an ndarray using the .shape attribute:



In [6]:
print(Ar.shape)

(2, 2)


In [7]:
print(Arreglo.shape)

(3, 2)


If we create an 2-dimensional array (i.e. matrix), each row can be accessed by index:



In [8]:
print(Ar[0])
print(Ar[1])

[1 3]
[2 4]


In [9]:
print(Arreglo[0])
print(Arreglo[1])

[8 7]
[6 5]


If we want to access the matrix by column instead:

In [10]:
print('the first column: ', Ar[:,0])
print('the second column: ', Ar[:,1])

the first column:  [1 2]
the second column:  [3 4]


In [11]:
print('La primera columna: ', Arreglo[:,0])
print('La segunda columna: ', Arreglo[:,1])

La primera columna:  [8 6 2]
La segunda columna:  [ 7  5 66]


#Array Functions
Some functions built in NumPy that allow us to perform calculations on arrays. For example, we can apply the natural logarithm to each element of an array:

In [12]:
print(np.log(price_array))

[4.96793654 4.98244156 4.9675886  4.96995218 4.96633504 4.96018375]


In [13]:
print(np.log(arreglo_precios))

[3.01700441 4.32849399 4.96060436 5.03708246 8.5666498  4.96018375]


Other functions return a single value:

In [14]:
print(np.mean(price_array))
print(np.std(price_array))
print(np.sum(price_array))
print(np.max(price_array))

143.89666666666668
0.9673790478515796
863.38
145.83


In [15]:
print(np.mean(arreglo_precios))
print(np.std(arreglo_precios))
print(np.sum(arreglo_precios))
print(np.max(arreglo_precios))

964.8466666666667
1918.5183297679373
5789.08
5253.5


The functions above return the mean, standard deviation, total and maximum value of an array.

#Pandas
Pandas is one of the most powerful tools for dealing with financial data. First we need to import Pandas:

In [16]:
import pandas as pd

#Series
Series is a one-dimensional labeled array capable of holding any data type (integers, strings, float, Python object, etc.)

We create a Series by calling pd.Series(data), where data can be a dictionary, an array or just a scalar value.

In [17]:
price = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
s = pd.Series(price)
s

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
dtype: float64

In [18]:
precios = [9983.2, 563.4, 143.68, 144.02, 633.5, 142.62]
serie = pd.Series(precios)
serie

0    9983.20
1     563.40
2     143.68
3     144.02
4     633.50
5     142.62
dtype: float64

We can customize the indices of a new Series:

In [19]:
s = pd.Series(price,index = ['a','b','c','d','e','f'])
s

a    143.73
b    145.83
c    143.68
d    144.02
e    143.50
f    142.62
dtype: float64

In [20]:
s1 = pd.Series(precios,index = ['lapiz','papel','corbata','borrador','boligrafo','marcador'])
s1

lapiz        9983.20
papel         563.40
corbata       143.68
borrador      144.02
boligrafo     633.50
marcador      142.62
dtype: float64

Or we can change the indices of an existing Series:

In [21]:
s.index = [6,5,4,3,2,1]
s

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64

In [22]:
s1.index = [7,8,9,10,11,12]
s1

7     9983.20
8      563.40
9      143.68
10     144.02
11     633.50
12     142.62
dtype: float64

Series is like a list since it can be sliced by index:

In [23]:
print(s[1:])
print(s[:-2])

5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64
6    143.73
5    145.83
4    143.68
3    144.02
dtype: float64


In [24]:
print(s1[2:])
print(s1[:-1])

9     143.68
10    144.02
11    633.50
12    142.62
dtype: float64
7     9983.20
8      563.40
9      143.68
10     144.02
11     633.50
dtype: float64


Series is also like a dictionary whose values can be set or fetched by index label:

In [25]:
print(s[4])
s[4] = 0
print(s)

143.68
6    143.73
5    145.83
4      0.00
3    144.02
2    143.50
1    142.62
dtype: float64


In [26]:
print(s1[0])
s1[3] = 10
print(s1)

KeyError: ignored

Series can also have a name attribute, which will be used when we make up a Pandas DataFrame using several series.

In [ ]:
s = pd.Series(price, name = 'Apple Price List')
print(s)
print(s.name)

In [ ]:
s2 = pd.Series(precios, name = 'Lista de Precios:')
print(s1)
print(s1.name)

We can get the statistical summaries of a Series:

In [ ]:
print(s2.describe())

#Time Index
Pandas has a built-in function specifically for creating date indices: pd.date_range(). We use it to create a new index for our Series:

In [ ]:
time_index = pd.date_range('2017-01-01',periods = len(s),freq = 'D')
print(time_index)
s.index = time_index
print(s)

In [ ]:
time_index = pd.date_range('2018-01-01',periods = len(s),freq = 'D')
print(time_index)
s2.index = time_index
print(s2)

Series are usually accessed using the iloc[] and loc[] methods. iloc[] is used to access elements by integer index, and loc[] is used to access the index of the series.

iloc[] is necessary when the index of a series are integers, take our previous defined series as example:



In [ ]:
s.index = [6,5,4,3,2,1]
print(s)
print(s[1])

In [ ]:
s2.index = [10,20,30,40,50,60]
print(s2)
print(s2[3])

If we intended to take the second element of the series, we would make a mistake here, because the index are integers. In order to access to the element we want, we use iloc[] here:



In [ ]:
print(s.iloc[1])

While working with time series data, we often use time as the index. Pandas provides us with various methods to access the data by time index.

In [ ]:
s.index = time_index
print(s['2017-01-03'])

In [ ]:
s2.index = time_index
print(s2['2018-01-03'])

We can even access to a range of dates:

In [ ]:
print(s['2017-01-02':'2017-01-05'])

In [ ]:
print(s2['2018-01-02':'2018-01-05'])

Series[] provides us a very flexible way to index data. We can add any condition in the square brackets:

In [ ]:
print(s[s < np.mean(s)] )
print([(s > np.mean(s)) & (s < np.mean(s) + 1.64*np.std(s))])

In [ ]:
print(s2[s2 < np.mean(s2)] )
print([(s2 > np.mean(s2)) & (s2 < np.mean(s2) + 1.64*np.std(s2))])

As demonstrated, we can use logical operators like & (and), | (or) and ~ (not) to group multiple conditions.

#Summary
Here we have introduced NumPy and Pandas for scientific computing in Python. In the next chapter, we will dive into Pandas to learn resampling and manipulating Pandas DataFrame, which are commonly used in financial data analysis.